spring.application.name=montreal-intelligence

spring.datasource.url=jdbc:postgresql://localhost:5432/montreal_intelligence
spring.datasource.username=gian
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration